version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - D:/docker/wnmp:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    links:
      - php-fpm
    extra_hosts:
      - ads.com:127.0.0.1
    container_name: nginx-server

  php-fpm:
    image: php:7.2-fpm
    build: ./php72
    links:
      - mysql
      - redis
    ports:
      - 9000:9000
    volumes:
      - D:/docker/wnmp:/usr/share/nginx/html
      - ./php72/conf/php.ini:/usr/local/etc/php/php.ini
      - ./php72/log:/etc/log/php.log/php/php.log
    container_name: php-server
    environment:
      DB_SERVER_HOST: 127.0.0.1
      MYSQL_DATABASE: mysql-server
      MYSQL_USER: php
      MYSQL_PASSWORD: php-mysql
      MYSQL_ROOT_PASSWORD: 123456
      PHP_TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - D:/docker/wnmp/mysql:/var/lib/mysql
      - /conf.d/mysql.conf.d:/etc/mysql/mysql.conf.d
    container_name: mysql-server
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql-server
      MYSQL_USER: php
      MYSQL_PASSWORD: php-mysql

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - D:/docker/wnmp/redis:/data
    container_name: redis-server